# Site settings
title: GUNGHI 개발 블로그
header-img: img/home-bg.jpg
email: siosio3103@gmail.com
copyright_name: Your/Project/GUNGHI
description: "이것저것 개발내용을 정리하는 블로그입니다"
baseurl: ""
url: "https://siosio3103.github.io"
github_username:  siosio34
facebook_username:  siosio34
email_username:  siosio3103@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
